//
//  LocationListRouter.swift
//  FindACity
//
//  Created by Nisum on 7/10/18.
//  Copyright (c) 2018 Orlando Arzola. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LocationListRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
    func routeToMap()
}

protocol LocationListDataPassing {
    var dataStore: LocationListDataStore? { get }
}

class LocationListRouter: NSObject, LocationListRoutingLogic, LocationListDataPassing {
    weak var viewController: LocationListViewController?
    var dataStore: LocationListDataStore?

    // MARK: Routing
    
    func routeToMap() {
        let destinationVC = viewController?.navigationController?.viewControllers.first(where: {$0 is MapViewController}) as! MapViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToMap(source: dataStore!, destination: &destinationDS)
        navigationToMap(source: viewController!)
    }

    //func routeToSomewhere(segue: UIStoryboardSegue?)
    //{
    //  if let segue = segue {
    //    let destinationVC = segue.destination as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //  } else {
    //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //    navigateToSomewhere(source: viewController!, destination: destinationVC)
    //  }
    //}

    // MARK: Navigation
    
    func navigationToMap(source: LocationListViewController) {
        source.navigationController?.popViewController(animated: true)
    }

    //func navigateToSomewhere(source: LocationListViewController, destination: SomewhereViewController)
    //{
    //  source.show(destination, sender: nil)
    //}

    // MARK: Passing data
    
    func passDataToMap(source: LocationListDataStore, destination: inout MapDataStore) {
        destination.city = source.city
        destination.isLocationSelected = true
    }

    //func passDataToSomewhere(source: LocationListDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
