//
//  LocationListInteractor.swift
//  FindACity
//
//  Created by Nisum on 7/10/18.
//  Copyright (c) 2018 Orlando Arzola. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LocationListBusinessLogic {
    func getLocations()
    func selectLocation(atIndexpath indexPath: IndexPath)
}

protocol LocationListDataStore {
    var countries: [Country] { get set }
    var cities: [City] { get set }
    var city: City? { get set }
}

class LocationListInteractor: LocationListBusinessLogic, LocationListDataStore {
    var cities: [City] = []
    var countries: [Country] = []
    var city: City?
    var locations: [(String, [City])] = []
    var presenter: LocationListPresentationLogic?
    
    func getLocations() {
        for country in countries {
            let currentCities = cities.filter({$0.countryCode == country.code})
            locations.append((country.name, currentCities))
        }
        let response = LocationList.Location.Response(locations: locations)
        presenter?.presentLocationList(response: response)
    }
    
    func selectLocation(atIndexpath indexPath: IndexPath) {
        city = locations[indexPath.section].1[indexPath.row]
    }
}
