//
//  LocationListWorker.swift
//  FindACity
//
//  Created by Nisum on 7/10/18.
//  Copyright (c) 2018 Orlando Arzola. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class LocationListWorker {
    func doSomeWork() {
    }
}
