# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FindACity' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Polyline', '~> 4.0'

  # Pods for FindACity

  target 'FindACityTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
