//
//  MapModels.swift
//  FindACity
//
//  Created by Nisum on 7/8/18.
//  Copyright (c) 2018 Orlando Arzola. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreLocation

enum Map {
    // MARK: Use cases

    enum PlaceMark {
        struct Request {
            var countryCode: String
            var cityCode: String
        }
        struct Response {
        }
        struct ViewModel {
        }
    }
    
    enum AlertView {
        struct ViewModel {
            var title: String
            var message: String
            var actionTitle: String
        }
    }
    
    enum Error {
        struct Response {
            var error: GlobalErrors
        }
    }
    
    enum Location {
        struct Response {
            var location: CLLocation
            var workingArea: [String]
        }
        struct ViewModel {
            var lat: Double
            var lon: Double
            var workingArea: [String]
        }
    }
    
    enum CurrentCity {
        struct ViewModel {
            var cityName: String
            var currency: String
            var language: String
        }
        struct Request {
            var city: City
            var country: String
        }
        struct Response {
            var city: City?
        }
    }
}
