//
//  MapRouter.swift
//  FindACity
//
//  Created by Nisum on 7/8/18.
//  Copyright (c) 2018 Orlando Arzola. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MapRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
    func routeToLocationList()
}

protocol MapDataPassing {
    var dataStore: MapDataStore? { get }
}

class MapRouter: NSObject, MapRoutingLogic, MapDataPassing {
    weak var viewController: MapViewController?
    var dataStore: MapDataStore?

    // MARK: Routing
    
    func routeToLocationList() {
        let locationListVC = LocationListViewController()
        var destinationDS = locationListVC.router!.dataStore!
        passDataToLocationList(source: dataStore!, destination: &destinationDS)
        navigateToLocationList(source: viewController!, destination: locationListVC)
    }

    // MARK: Navigation
    
    func navigateToLocationList(source: MapViewController, destination: LocationListViewController) {
        destination.delegate = source
        source.navigationController?.pushViewController(destination, animated: true)
    }

    // MARK: Passing data
    
    func passDataToLocationList(source: MapDataStore, destination: inout LocationListDataStore) {
        destination.cities = source.cities
        destination.countries = source.countries
    }
}
