//
//  MapWorker.swift
//  FindACity
//
//  Created by Nisum on 7/8/18.
//  Copyright (c) 2018 Orlando Arzola. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class MapWorker {
    func doSomeWork() {
    }
    
    let apiLocationService: APILocationService
    
    init(apiLocationService: APILocationService = APILocation()) {
        self.apiLocationService = apiLocationService
    }
    
    func getCities(onSuccess: @escaping (_ cities: [City]?) -> Void) {
        apiLocationService.getCities(onSuccess: onSuccess)
    }

    func getCountries(onSuccess: @escaping (_ countries: [Country]?) -> Void) {
        apiLocationService.getCountry(onSuccess: onSuccess)
    }
    
    func getCity(withId id: String, onSuccess: @escaping (_ city: City?) -> Void) {
        apiLocationService.findCity(withId: id, onSuccess: onSuccess)
    }
}
